####################################
# Macros
####################################
# There are several provided macros to help with formatting.
# These macros are usable in the "Description" and "*Notes" fields
# Raw HTML is also supported in all fields, but is only recommended
# for use in the aforementioned fields. (Commas or parenthesis
# within macro arguments can be escaped with a backslash)
#
# Valid buttons are p, k, s, h, taunt, and additionally, x (gray), or (black), and generic (inherit)
# Invalid buttons will be rendered as a generic button.
#
# %ref(<move name>, <display>, <button>) - Creates a link to another move
#   Outputs: <a href="#movename" class="ref" button="button" title="movename">display</a>
#
# %btn(<button>, <text>) - Colors <text> to match the color of <button>
#   Outputs: <em class="btn" button="button">text</em>
#
# %img(<path>, <alt>, <notes>) - Inserts an image with a caption where <path> is the path to the image relative to the
#   character's directory, and <notes> is any notes to display underneath the image
#   Outputs: <div class=embed><img src="../images/???/path" alt="alt" title="path"><p>notes</p></div>
#
# %link(<url>, <alt>, <text>) - Creates a hyperlink to <url> with the display text <text>, where <url> is the link URL
#   relative to the root of the site
#   Outputs: <a href="../url" totle="alt">text</a>

[Character]
Name=""
Description="""
"""
IconPath=""         # Path to icon (relative to character's directory)
PortraitPath=""     # Path to portrait art
#Health=""           # The amount of health the character has
#DamageMod=""        # The amount of damage this character takes
Type=""             # Fighting style
#FastestAttacks=[]   # The fastest moves this character has
Reversals=[]        # List of moves with invulnerable startup

###################################
# Unique Mechanics
###################################
[[Character.Mechanics]] # Custom mechanic with a summary of its effects
Name=""
Description="""
"""

###################################
# Command Normals
###################################
[[Character.Normals]]
Input=""            # Input string
Button=""           # Any of p, k, s, x, or taunt
AirOK=false         # Can this be used in the air?
HoldOK=false        # Can this be held?
Condition=""        # Does this move have any special requirements?
Images=[""]         # Featured move sprites
ImageNotes=[""]     # Notes for each featured move sprite
Hitboxes=[""]       # Hitboxes for this move
HitboxNotes=[""]    # Notes for each hitbox
Description="""
"""

[[Character.Normals.Data]] # todo: this might get moved into a separate frame data file
Version=""          # The version of this move to display
Damage=""           # How much does this move deal?
Guard=""            # Where the opponent can block this move
Startup=""          # How many frames it takes to start the move
Active=""           # How many frames the move is active
Recovery=""         # How many frames it takes to recover from the move
OnBlock=""          # The advantage or disadvantage on block
OnHit=""            # The advantage or disadvantage on hit
Invuln=[""]         # Where and how is this move invulnerable?
SpecialFrames=[""]  # Is there something of note for a specific frame?
SpecialNote=""      # What's so special about them?
# todo: Attributes section, displays projectile status, knockdown type, etc.

###################################
# Special Attacks
###################################
[[Character.Specials]]
Name=""
Inputs=[""]         # The input strings. A value of ["236P", "K"] will display as "236P/K"
Buttons=[""]        # The button for each input, should match the order of the above list
Condition=""        # Special requirements for the move, displayed after input string
Images=[""]         # Featured move sprites
ImageNotes=[""]     # Notes for each featured move sprite
Hitboxes=[""]       # Hitboxes for this move
HitboxNotes=[""]    # Notes for each hitbox
Description="""
"""

###################################
# Supers
###################################
[[Character.Supers]]
Name=""
Inputs=[""]         # The input strings. A value of ["236236P", "K"] will display as "236236P/K"
Buttons=[""]        # The button for each input, should match the order of the above list
Condition=""        # Will mostly be "with 50% meter" in the case of supers
Images=[""]         # Featured move sprites
ImageNotes=[""]     # Notes for each featured move sprite
Hitboxes=[""]       # Hitboxes for this move
HitboxNotes=[""]    # Notes for each hitbox
Description="""
"""

